#########################################
# Private AI Services Rules
# GitHub: https://github.com/hsuyelin/surge-conf
#########################################

# Factory AI
DOMAIN-SUFFIX,factory.ai

# AI Services
DOMAIN-KEYWORD,cursor
DOMAIN-KEYWORD,stripe
DOMAIN-SUFFIX,servd-anthropic-website.b-cdn.net
DOMAIN-SUFFIX,anthropic.com
DOMAIN-SUFFIX,claude.ai
DOMAIN-SUFFIX,claudeusercontent.com
DOMAIN-SUFFIX,intercomcdn.com
DOMAIN-SUFFIX,cdn.usefathom.com

# Gemini
DOMAIN-SUFFIX,sheerid.com
