#########################################
# Private Proxy Rules
# GitHub: https://github.com/hsuyelin/surge-conf
#########################################

# Final
DOMAIN,1key.me
DOMAIN-SUFFIX,windows.net
DOMAIN-SUFFIX,steampowered.com
DOMAIN-SUFFIX,anyrouter.top
DOMAIN-SUFFIX,superdesign.dev
DOMAIN-KEYWORD,onnxruntime

# Reddit
DOMAIN-SUFFIX,reddit.com

# Github
DOMAIN,github.com

# DIA
DOMAIN-SUFFIX,diabrowser.engineering
