#########################################
# Private Emby Services Rules
# GitHub: https://github.com/hsuyelin/surge-conf
#########################################

# Emby Services
DOMAIN-KEYWORD,omni
DOMAIN,emby.lolicon.life
DOMAIN,onyra.43992026.xyz
DOMAIN,mp.onyra.icu
DOMAIN,8s2hbg4.onyra.cc
DOMAIN,fws7z.onyra.cc
DOMAIN,bps8m.onyra.cc
DOMAIN,nano.jmsuper.com
