#########################################
# Private Server IPs Rules
# GitHub: https://github.com/hsuyelin/surge-conf
#########################################

# Server IPs
IP-CIDR,184.107.122.19/32,no-resolve
IP-CIDR,184.107.122.228/32,no-resolve
IP-CIDR,95.216.26.180/32,no-resolve
IP-CIDR,167.148.203.113/32,no-resolve
