#########################################
# Private Google Services Rules
# GitHub: https://github.com/hsuyelin/surge-conf
#########################################

# Google
DOMAIN-KEYWORD,antigravity
DOMAIN,goo.gle
